description: Parameters used to train a CNN for the BFF problem

# Settings for data preprocessing
# IMPORTANT - avoid changing these data_parameters (other than the file paths), unless you really
# understand the consequences in the code. Most parameters came from the ray-tracing simulations
# themselves
data_parameters:
    #input_file: '../data_preprocessing/data_processed/final_table'
    input_file: '../local_run/data/final_table'
    preprocessed_file: '../local_run/data/preprocessed_dataset'
    max_time: 6
    sample_freq: 20
    beamformings: 32
    power_offset: 170
    power_scale: 0.01
    pos_grid: [400.0, 400.0]
    pos_shift: [183.0, 176.0]
    keep_timeslots: [1, 82]
    run_sanity_checks: True

# Settings for overall experiment control
experiment_settings:
    model_type: "cnn"

# Settings for model hyperparameters
ml_parameters:
    # IO settings
    input_name: "input"
    input_shape: [32, 81, 1]   #BF, usable timeslots, 1 "data channel"
    output_name: "location"
    output_type: "regression"
    output_shape: 2

    # basic model hyperparams
    batch_size: 64
    batch_size_inference: 256
    dropout: 0.01
    epochs: 1000    #max number of epochs
    fc_layers: 12
    fc_neurons: 256
    learning_rate: 0.0001
    learning_rate_decay: 0.995  #multiplicative term at the end of each epoch
    target_gpu: "0"

    # architecture specific hyperparams
    conv_layers: 1
    conv_filters: [8]
    conv_filter_size: [[3, 3]]
    conv_maxpool: [[2, 1]]
